version: 2
updates:
  - package-ecosystem: "swift"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Boise"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
    groups:
      swift-packages:
        patterns:
          - "*"
