import SwiftData
import XCTest
@testable import Tally

final class CSVTransactionImporterTests: XCTestCase {
    var fixturesDirectory: URL {
        URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .appendingPathComponent("Fixtures", isDirectory: true)
    }

    func testDraftDetectionAndMaterialization() throws {
        let importer = CSVTransactionImporter()
        let csv = """
        Posted Date,Description,Amount,Account
        01/01/2025,Netflix,-15.49,Test Card B
        02/01/2025,Netflix,-15.49,Test Card B
        """

        let draft = try importer.makeDraft(fileName: "ledger.csv", csvText: csv)

        XCTAssertEqual(draft.suggestedMapping.dateColumn, "Posted Date")
        XCTAssertEqual(draft.suggestedMapping.amountColumn, "Amount")
        XCTAssertEqual(draft.suggestedMapping.descriptionColumn, "Description")
        XCTAssertEqual(draft.previewRows.count, 2)

        let transactions = try importer.materializeTransactions(from: draft, mapping: draft.suggestedMapping)

        XCTAssertEqual(transactions.count, 2)
        XCTAssertEqual(transactions.first?.merchantRaw, "Netflix")
        XCTAssertEqual(transactions.first?.accountName, "Test Card B")
    }

    func testQuotedFieldsAndPositiveDebitConvention() throws {
        let importer = CSVTransactionImporter()
        let csv = """
        Date,Vendor,Charge
        2025-01-01,"Spotify, Family",10.99
        2025-02-01,"Spotify, Family",10.99
        """

        let draft = try importer.makeDraft(fileName: "quoted.csv", csvText: csv)
        var mapping = draft.suggestedMapping
        mapping.debitSignConvention = .positive

        let transactions = try importer.materializeTransactions(from: draft, mapping: mapping)

        XCTAssertEqual(transactions.first?.merchantRaw, "Spotify, Family")
        XCTAssertEqual(transactions.first?.transactionAmount, Decimal(string: "-10.99"))
    }

    func testQuotedFieldsSupportEscapedQuotesAndEmbeddedNewlines() throws {
        let importer = CSVTransactionImporter()
        let csv = #"""
        Date,Vendor,Amount,Memo
        2025-01-01,"Acme ""Pro""",-12.00,"Plan ""A""
        renewed"
        """#

        let draft = try importer.makeDraft(fileName: "escaped.csv", csvText: csv)
        let transactions = try importer.materializeTransactions(from: draft, mapping: draft.suggestedMapping)

        XCTAssertEqual(transactions.count, 1)
        XCTAssertEqual(transactions.first?.merchantRaw, #"Acme "Pro""#)
        XCTAssertEqual(transactions.first?.memo, "Plan \"A\"\nrenewed")
    }

    func testParserSupportsCRLFAndSemicolonDelimitedFiles() throws {
        let importer = CSVTransactionImporter()
        let csv = [
            "Date;Merchant;Amount;Account",
            "2025-01-01;Netflix;-15.49;Test Card B",
            "2025-02-01;Spotify;-10.99;Test Card A"
        ].joined(separator: "\r\n") + "\r\n"

        let draft = try importer.makeDraft(fileName: "semicolon.csv", csvText: csv)
        let transactions = try importer.materializeTransactions(from: draft, mapping: draft.suggestedMapping)

        XCTAssertEqual(draft.headers, ["Date", "Merchant", "Amount", "Account"])
        XCTAssertEqual(draft.suggestedMapping.amountColumn, "Amount")
        XCTAssertEqual(draft.suggestedMapping.merchantColumn, "Merchant")
        XCTAssertEqual(transactions.count, 2)
        XCTAssertEqual(transactions.first?.merchantRaw, "Netflix")
    }

    func testDraftDetectionSkipsLeadingPreambleRows() throws {
        let importer = CSVTransactionImporter()
        let csv = """
        Export generated by Example Bank
        Account,Test Card B
        Date,Merchant,Amount,Account
        2025-01-01,Netflix,-15.49,Test Card B
        2025-02-01,Spotify,-10.99,Test Card B
        """

        let draft = try importer.makeDraft(fileName: "preamble.csv", csvText: csv)
        let validation = TabularTransactionDraftBuilder().previewValidation(
            for: draft,
            mapping: draft.suggestedMapping
        )
        let transactions = try importer.materializeTransactions(from: draft, mapping: draft.suggestedMapping)

        XCTAssertEqual(draft.headers, ["Date", "Merchant", "Amount", "Account"])
        XCTAssertEqual(transactions.count, 2)
        XCTAssertTrue(
            validation.warnings.contains {
                $0.localizedCaseInsensitiveContains("skipped 2 leading")
            }
        )
    }

    func testDraftDetectionSkipsPreambleBeforeDayFirstRows() throws {
        let importer = CSVTransactionImporter()
        let csv = """
        Export generated by Example Bank
        Account,Test Card B
        Date,Merchant,Amount,Account
        13/01/2025,Netflix,-15.49,Test Card B
        14/02/2025,Spotify,-10.99,Test Card B
        """

        let draft = try importer.makeDraft(fileName: "day-first-preamble.csv", csvText: csv)
        let transactions = try importer.materializeTransactions(from: draft, mapping: draft.suggestedMapping)

        XCTAssertEqual(draft.headers, ["Date", "Merchant", "Amount", "Account"])
        XCTAssertEqual(transactions.count, 2)
        XCTAssertEqual(transactions.first?.merchantRaw, "Netflix")
    }

    func testFallbackDecodedCSVWarnsWhenTextLooksGarbled() throws {
        let temporaryURL = FileManager.default.temporaryDirectory
            .appendingPathComponent(UUID().uuidString)
            .appendingPathExtension("csv")
        var data = Data("Date,Merchant,Amount\n2025-01-01,Netflix ".utf8)
        data.append(contentsOf: [0xC3, 0xA9, 0x20, 0x96])
        data.append(Data(",-15.49\n".utf8))
        try data.write(to: temporaryURL)
        defer { try? FileManager.default.removeItem(at: temporaryURL) }

        let outcome = ImportPreparationService.prepareDraft(from: temporaryURL)
        guard case let .success(draft) = outcome else {
            return XCTFail("Expected import preparation to continue with a warning")
        }

        let validation = TabularTransactionDraftBuilder().previewValidation(
            for: draft,
            mapping: draft.suggestedMapping
        )
        XCTAssertTrue(
            validation.warnings.contains {
                $0.localizedCaseInsensitiveContains("encoding")
            }
        )
    }

    func testDraftDetectionSupportsTransactionExportsWithStatementAndNotesColumns() throws {
        let importer = CSVTransactionImporter()
        let marketplaceNotes = """
        2 x Example Personal Care Item - $30.00

        https://example.test/orders/TALLY-ORDER-0001
        """
        let marketplaceRow = [
            "2026-02-27",
            "Example Marketplace",
            "Personal Care",
            "Test Rewards Card 0001",
            "EXAMPLE MARKETPLACE TEST BILL WA",
            "\"\(marketplaceNotes)\"",
            "-63.60",
            "Retail Sync",
            "Shared",
            ""
        ].joined(separator: ",")
        let csv = """
        Date,Merchant,Category,Account,Original Statement,Notes,Amount,Tags,Owner,Business Entity
        2026-03-13,Fictional Grocery Co-op,Groceries,Test Credit Card 0002,FICTIONAL GROCERY COOP,,-41.00,,Shared,
        \(marketplaceRow)
        """

        let draft = try importer.makeDraft(fileName: "Transactions.csv", csvText: csv)

        XCTAssertEqual(draft.suggestedMapping.dateColumn, "Date")
        XCTAssertEqual(draft.suggestedMapping.amountColumn, "Amount")
        XCTAssertEqual(draft.suggestedMapping.merchantColumn, "Merchant")
        XCTAssertEqual(draft.suggestedMapping.descriptionColumn, "Original Statement")
        XCTAssertEqual(draft.suggestedMapping.categoryColumn, "Category")
        XCTAssertEqual(draft.suggestedMapping.accountColumn, "Account")
        XCTAssertEqual(draft.previewRows.count, 2)

        let transactions = try importer.materializeTransactions(from: draft, mapping: draft.suggestedMapping)

        XCTAssertEqual(transactions.count, 2)
        XCTAssertEqual(transactions.first?.merchantRaw, "Example Marketplace")
        XCTAssertEqual(transactions.first?.accountName, "Test Rewards Card 0001")
        XCTAssertEqual(transactions.first?.memo, "EXAMPLE MARKETPLACE TEST BILL WA")
        XCTAssertEqual(transactions.first?.transactionAmount, Decimal(string: "-63.60"))
    }

    func testDraftDetectionCanInferDateAndAmountColumnsFromValues() throws {
        let importer = CSVTransactionImporter()
        let csv = """
        Booked,Who,Spent,Wallet
        2025-01-01,Netflix,-15.49,Test Card B
        2025-02-01,Spotify,-10.99,Test Card A
        """

        let draft = try importer.makeDraft(fileName: "unknown-schema.csv", csvText: csv)
        let transactions = try importer.materializeTransactions(from: draft, mapping: draft.suggestedMapping)

        XCTAssertEqual(draft.suggestedMapping.dateColumn, "Booked")
        XCTAssertEqual(draft.suggestedMapping.amountColumn, "Spent")
        XCTAssertEqual(draft.suggestedMapping.merchantColumn, "Who")
        XCTAssertEqual(draft.suggestedMapping.accountColumn, "Wallet")
        XCTAssertEqual(transactions.count, 2)
        XCTAssertEqual(transactions.first?.merchantRaw, "Netflix")
    }

    func testPreviewValidationWarnsWhenDebitSignWouldHideCharges() throws {
        let importer = CSVTransactionImporter()
        let csv = """
        Date,Merchant,Amount
        2025-01-01,Netflix,15.49
        2025-02-01,Netflix,15.49
        """

        let draft = try importer.makeDraft(fileName: "positive-ledger.csv", csvText: csv)
        var mapping = draft.suggestedMapping
        mapping.debitSignConvention = .negative

        let validation = TabularTransactionDraftBuilder().previewValidation(for: draft, mapping: mapping)

        XCTAssertEqual(validation.parseableRowCount, 2)
        XCTAssertEqual(validation.usableMerchantRowCount, 2)
        XCTAssertEqual(validation.debitRowCount, 0)
        XCTAssertTrue(
            validation.warnings.contains {
                $0.localizedCaseInsensitiveContains("subscription detection will skip them")
            }
        )
    }

    func testMaterializationSkipsUnreadableRowsAndReportsCount() throws {
        let importer = CSVTransactionImporter()
        let csv = """
        Date,Merchant,Amount
        2025-01-01,Netflix,-15.49
        notadate,Spotify,-10.99
        2025-03-01,Hulu,notanamount
        2025-04-01,Disney,-9.99
        """

        let draft = try importer.makeDraft(fileName: "messy.csv", csvText: csv)
        let result = try importer.materializeSeeds(from: draft, mapping: draft.suggestedMapping)

        XCTAssertEqual(result.seeds.count, 2)
        XCTAssertEqual(result.skippedRowCount, 2)
        XCTAssertEqual(result.seeds.first?.merchantRaw, "Netflix")
        XCTAssertEqual(result.seeds.last?.merchantRaw, "Disney")
    }

    func testDayFirstDatesAreDisambiguatedPerImport() throws {
        let importer = CSVTransactionImporter()
        let csv = """
        Date,Merchant,Amount
        13/02/2025,Netflix,-15.49
        05/03/2025,Spotify,-10.99
        """

        let draft = try importer.makeDraft(fileName: "day-first.csv", csvText: csv)
        let transactions = try importer.materializeTransactions(from: draft, mapping: draft.suggestedMapping)

        var calendar = Calendar(identifier: .gregorian)
        calendar.timeZone = .current
        let first = calendar.dateComponents([.year, .month, .day], from: transactions[0].transactionDate)
        let second = calendar.dateComponents([.year, .month, .day], from: transactions[1].transactionDate)

        // A leading 13 forces day-first, so 05/03/2025 is 5 March, not 3 May.
        XCTAssertEqual(first.month, 2)
        XCTAssertEqual(first.day, 13)
        XCTAssertEqual(second.month, 3)
        XCTAssertEqual(second.day, 5)
    }

    func testAmbiguousDatesDefaultToMonthFirst() {
        let parser = TransactionFieldParser()
        let order = TransactionFieldParser.inferDateComponentOrder(fromSamples: ["05/03/2025", "06/07/2025"])
        XCTAssertEqual(order, .monthFirst)

        var calendar = Calendar(identifier: .gregorian)
        calendar.timeZone = .current
        let date = try? XCTUnwrap(parser.tryParseDate("05/03/2025"))
        let components = calendar.dateComponents([.month, .day], from: date ?? .distantPast)
        XCTAssertEqual(components.month, 5)
        XCTAssertEqual(components.day, 3)
    }

    func testParserSupportsAdditionalDateFormats() {
        let parser = TransactionFieldParser()
        XCTAssertNotNil(parser.tryParseDate("2025/03/05"))
        XCTAssertNotNil(parser.tryParseDate("05.03.2025"))
        XCTAssertNotNil(parser.tryParseDate("05-03-2025"))
        XCTAssertNotNil(parser.tryParseDate("3/5/25"))
        XCTAssertNotNil(parser.tryParseDate("2025-03-05 13:45:00"))
        XCTAssertNotNil(parser.tryParseDate("2025-03-05T13:45:00"))
    }

    func testParserHandlesEuropeanDecimalCommaAndCurrencies() throws {
        let parser = TransactionFieldParser()
        XCTAssertEqual(parser.tryParseAmount("1.234,56"), Decimal(string: "1234.56"))
        XCTAssertEqual(parser.tryParseAmount("1234,56"), Decimal(string: "1234.56"))
        XCTAssertEqual(parser.tryParseAmount("1,234.56"), Decimal(string: "1234.56"))
        XCTAssertEqual(parser.tryParseAmount("€1.234,56"), Decimal(string: "1234.56"))
        XCTAssertEqual(parser.tryParseAmount("$1,234.56"), Decimal(string: "1234.56"))
        XCTAssertEqual(parser.tryParseAmount("12.50 USD"), Decimal(string: "12.50"))
        XCTAssertEqual(parser.tryParseAmount("-£12.00"), Decimal(string: "-12.00"))
        XCTAssertEqual(parser.tryParseAmount("(45,00)"), Decimal(string: "-45.00"))
    }

    func testMappingIsLowConfidenceWhenNoAmountColumnParses() throws {
        let importer = CSVTransactionImporter()
        let csv = """
        Date,Merchant,Note
        2025-01-01,Netflix,hello
        2025-02-01,Spotify,world
        """

        let draft = try importer.makeDraft(fileName: "no-amount.csv", csvText: csv)

        XCTAssertLessThan(draft.confidence, 0.7)

        let validation = TabularTransactionDraftBuilder().previewValidation(
            for: draft,
            mapping: draft.suggestedMapping
        )
        XCTAssertEqual(validation.parseableRowCount, 0)
        XCTAssertTrue(
            validation.warnings.contains {
                $0.localizedCaseInsensitiveContains("does not produce any parseable")
            }
        )
    }

    @MainActor
    func testBulkImportCompletesForLargeMerchantSet() async throws {
        let importer = CSVTransactionImporter()
        let container = try ModelContainerFactory.makeSharedContainer(inMemoryOnly: true)
        let context = container.mainContext
        let appModel = AppModel.testing()

        var csvLines = ["Date,Merchant,Category,Account,Original Statement,Notes,Amount,Tags"]
        for index in 0..<300 {
            let date = String(format: "2026-03-%02d", (index % 28) + 1)
            csvLines.append(
                "\(date),Merchant \(index),Software,Visa,Merchant \(index),,-\(index + 1).00,"
            )
        }

        let draft = try importer.makeDraft(fileName: "bulk.csv", csvText: csvLines.joined(separator: "\n"))
        appModel.importDraft = draft

        await appModel.commitImport(using: draft.suggestedMapping, into: context)

        XCTAssertNil(appModel.importErrorMessage)
        XCTAssertEqual(
            appModel.infoMessage,
            "Imported 300 transactions from bulk.csv (300 new, 0 updated, 0 unchanged). Found 0 subscriptions and 0 items to review."
        )
        XCTAssertTrue(appModel.classificationStatusMessage?.contains("Gemma is unavailable") == true)
        XCTAssertTrue(appModel.classificationStatusMessage?.contains("Falling back") == true)
        XCTAssertTrue(appModel.classificationStatusMessage?.contains("300 unique merchants") == true)

        let transactions = try context.fetch(FetchDescriptor<NormalizedTransaction>())
        XCTAssertEqual(transactions.count, 300)

        let classifications = try context.fetch(FetchDescriptor<MerchantClassification>())
        XCTAssertEqual(classifications.count, 300)
        XCTAssertTrue(classifications.allSatisfy { $0.classifierVersion == 0 })

        let importRecords = try context.fetch(FetchDescriptor<ImportRecord>())
        XCTAssertEqual(importRecords.first?.importedTransactionCount, 300)
        XCTAssertEqual(importRecords.first?.detectedSubscriptionCount, 0)
        XCTAssertEqual(importRecords.first?.needsReviewSubscriptionCount, 0)
        XCTAssertEqual(importRecords.first?.status, .analyzed)
    }

    func testLargeMerchantSetUsesProviderBatchStrategy() {
        let engine = MerchantClassificationEngine()

        XCTAssertEqual(engine.strategy(forUniqueMerchantCount: 300), .providerBatch)
        XCTAssertEqual(engine.strategy(forUniqueMerchantCount: 10), .individual)
    }

    func testLargeGemmaBatchUsesProviderClassificationWhenAvailable() async throws {
        let intelligence = RecordingMerchantClassificationIntelligence()
        let engine = MerchantClassificationEngine(intelligence: intelligence)
        let requests = (0..<30).map { index in
            MerchantClassificationRequest(
                rawMerchant: "Merchant \(index)",
                memo: nil,
                category: "Software",
                amount: Decimal(index + 1)
            )
        }

        let result = try await engine.classifyBatch(requests, strategy: .providerBatch)
        let recordedBatchSizes = await intelligence.batchSizes()

        XCTAssertEqual(result.strategyUsed, .providerBatch)
        XCTAssertNil(result.fallbackReason)
        XCTAssertEqual(result.results.count, requests.count)
        XCTAssertEqual(result.currentCacheableRawMerchants, Set(requests.map(\.rawMerchant)))
        XCTAssertEqual(recordedBatchSizes, [20, 10])
        XCTAssertEqual(result.results["Merchant 0"]?.canonicalName, "Merchant 0")
    }

    func testReadyProviderFailureReportsAttemptedFallback() async throws {
        let defaults = UserDefaults(suiteName: "CSVTransactionImporterTests.providerFailure")!
        defaults.removePersistentDomain(forName: "CSVTransactionImporterTests.providerFailure")
        let preferences = AIProviderPreferences(userDefaults: defaults)
        preferences.selectedKind = .gemmaLocal
        let engine = MerchantClassificationEngine(
            preferences: preferences,
            gemmaModelManager: try makeReadyGemmaModelManager(),
            intelligence: FailingMerchantClassificationIntelligence()
        )
        let requests = [
            MerchantClassificationRequest(
                rawMerchant: "Mystery Merchant",
                memo: "Monthly plan",
                category: "Software",
                amount: Decimal(string: "12.99") ?? 12.99
            )
        ]

        let result = try await engine.classifyBatch(requests, strategy: .individual)
        let summary = engine.availabilitySummary(
            for: result.strategyUsed,
            uniqueMerchantCount: requests.count,
            fallbackReason: result.fallbackReason
        )

        XCTAssertEqual(result.strategyUsed, .heuristicOnly)
        XCTAssertEqual(result.fallbackReason, .providerFailed)
        XCTAssertTrue(result.currentCacheableRawMerchants.isEmpty)
        XCTAssertTrue(summary.localizedStandardContains("attempted"))
        XCTAssertTrue(summary.localizedStandardContains("could not complete"))
        XCTAssertFalse(summary.localizedStandardContains("confident enough"))
    }

    func testPartialProviderBatchFailureReportsHeuristicFallback() async throws {
        let defaults = UserDefaults(suiteName: "CSVTransactionImporterTests.partialBatchFailure")!
        defaults.removePersistentDomain(forName: "CSVTransactionImporterTests.partialBatchFailure")
        let preferences = AIProviderPreferences(userDefaults: defaults)
        preferences.selectedKind = .gemmaLocal
        let engine = MerchantClassificationEngine(
            preferences: preferences,
            gemmaModelManager: try makeReadyGemmaModelManager(),
            intelligence: PartiallyFailingBatchMerchantClassificationIntelligence()
        )
        let requests = (0..<30).map { index in
            MerchantClassificationRequest(
                rawMerchant: "Merchant \(index)",
                memo: nil,
                category: "Software",
                amount: Decimal(index + 1)
            )
        }

        let result = try await engine.classifyBatch(requests, strategy: .providerBatch)
        let summary = engine.availabilitySummary(
            for: result.strategyUsed,
            uniqueMerchantCount: requests.count,
            fallbackReason: result.fallbackReason
        )

        XCTAssertEqual(result.strategyUsed, .providerBatch)
        XCTAssertEqual(result.fallbackReason, .partialProviderFailure)
        XCTAssertEqual(result.results.count, requests.count)
        XCTAssertEqual(result.currentCacheableRawMerchants.count, 20)
        XCTAssertTrue(result.currentCacheableRawMerchants.contains("Merchant 0"))
        XCTAssertFalse(result.currentCacheableRawMerchants.contains("Merchant 29"))
        XCTAssertTrue(summary.localizedStandardContains("heuristic fallback"))
    }

    func testSubsetProviderBatchResponseReportsHeuristicFallback() async throws {
        let defaults = UserDefaults(suiteName: "CSVTransactionImporterTests.subsetBatchResponse")!
        defaults.removePersistentDomain(forName: "CSVTransactionImporterTests.subsetBatchResponse")
        let preferences = AIProviderPreferences(userDefaults: defaults)
        preferences.selectedKind = .gemmaLocal
        let engine = MerchantClassificationEngine(
            preferences: preferences,
            gemmaModelManager: try makeReadyGemmaModelManager(),
            intelligence: SubsetBatchMerchantClassificationIntelligence()
        )
        let requests = (0..<30).map { index in
            MerchantClassificationRequest(
                rawMerchant: "Merchant \(index)",
                memo: nil,
                category: "Software",
                amount: Decimal(index + 1)
            )
        }

        let result = try await engine.classifyBatch(requests, strategy: .providerBatch)
        let summary = engine.availabilitySummary(
            for: result.strategyUsed,
            uniqueMerchantCount: requests.count,
            fallbackReason: result.fallbackReason
        )

        XCTAssertEqual(result.strategyUsed, .providerBatch)
        XCTAssertEqual(result.fallbackReason, .partialProviderFailure)
        XCTAssertEqual(result.results.count, requests.count)
        XCTAssertEqual(result.results["Merchant 0"]?.canonicalName, "Merchant 0")
        XCTAssertEqual(result.results["Merchant 1"]?.canonicalName, "AI Merchant 1")
        XCTAssertFalse(result.currentCacheableRawMerchants.contains("Merchant 0"))
        XCTAssertTrue(result.currentCacheableRawMerchants.contains("Merchant 1"))
        XCTAssertTrue(summary.localizedStandardContains("heuristic fallback"))
    }

    func testProviderBatchCancellationPropagatesWithoutRemainingBatches() async {
        let intelligence = CancellingBatchMerchantClassificationIntelligence()
        let engine = MerchantClassificationEngine(intelligence: intelligence)
        let requests = (0..<30).map { index in
            MerchantClassificationRequest(
                rawMerchant: "Merchant \(index)",
                memo: nil,
                category: "Software",
                amount: Decimal(index + 1)
            )
        }

        do {
            _ = try await engine.classifyBatch(requests, strategy: .providerBatch)
            XCTFail("Expected cancellation to propagate")
        } catch is CancellationError {
            let batchCallCount = await intelligence.batchCallCount()
            XCTAssertEqual(batchCallCount, 1)
        } catch {
            XCTFail("Expected CancellationError, got \(error)")
        }
    }

    func testIndividualProviderCancellationPropagatesWithoutContinuingMerchants() async {
        let intelligence = CancellingIndividualMerchantClassificationIntelligence()
        let engine = MerchantClassificationEngine(intelligence: intelligence)
        let requests = (0..<3).map { index in
            MerchantClassificationRequest(
                rawMerchant: "Merchant \(index)",
                memo: nil,
                category: "Software",
                amount: Decimal(index + 1)
            )
        }

        do {
            _ = try await engine.classifyBatch(requests, strategy: .individual)
            XCTFail("Expected cancellation to propagate")
        } catch is CancellationError {
            let merchantCallCount = await intelligence.merchantCallCount()
            XCTAssertEqual(merchantCallCount, 1)
        } catch {
            XCTFail("Expected CancellationError, got \(error)")
        }
    }

    func testSingleProviderCancellationPropagates() async {
        let intelligence = CancellingIndividualMerchantClassificationIntelligence()
        let engine = MerchantClassificationEngine(intelligence: intelligence)

        do {
            _ = try await engine.classify(
                rawMerchant: "Merchant 0",
                memo: nil,
                category: "Software",
                amount: 1
            )
            XCTFail("Expected cancellation to propagate")
        } catch is CancellationError {
            let merchantCallCount = await intelligence.merchantCallCount()
            XCTAssertEqual(merchantCallCount, 1)
        } catch {
            XCTFail("Expected CancellationError, got \(error)")
        }
    }

    func testXLSXDraftDetectionAndMaterialization() throws {
        let importer = XLSXTransactionImporter()
        let workbookURL = fixturesDirectory.appendingPathComponent("SampleImport.xlsx")

        let draft = try importer.makeDraft(fileName: "SampleImport.xlsx", fileURL: workbookURL)
        let transactions = try importer.materializeTransactions(from: draft, mapping: draft.suggestedMapping)

        XCTAssertEqual(draft.headers, ["Date", "Vendor", "Amount", "Category", "Account", "Memo"])
        XCTAssertEqual(transactions.count, 3)
        XCTAssertEqual(transactions.first?.merchantRaw, "Netflix")
        XCTAssertEqual(transactions.last?.merchantRaw, "Spotify")
    }

    func testXLSDraftDetectionAndMaterialization() throws {
        let importer = XLSBinaryTransactionImporter()
        let workbookURL = fixturesDirectory.appendingPathComponent("SampleImport.xls")

        let draft = try importer.makeDraft(fileName: "SampleImport.xls", fileURL: workbookURL)
        let transactions = try CSVTransactionImporter().materializeTransactions(
            from: draft,
            mapping: draft.suggestedMapping
        )

        XCTAssertEqual(draft.headers, ["Date", "Vendor", "Amount", "Category", "Account", "Memo"])
        XCTAssertEqual(transactions.count, 3)
        XCTAssertEqual(transactions.first?.merchantRaw, "Netflix")
        XCTAssertEqual(transactions.last?.merchantRaw, "Spotify")
    }

    func testMalformedXLSXReturnsReadableError() throws {
        let importer = XLSXTransactionImporter()
        let invalidURL = FileManager.default.temporaryDirectory
            .appendingPathComponent(UUID().uuidString)
            .appendingPathExtension("xlsx")
        try Data("not a workbook".utf8).write(to: invalidURL)
        defer { try? FileManager.default.removeItem(at: invalidURL) }

        XCTAssertThrowsError(
            try importer.makeDraft(fileName: invalidURL.lastPathComponent, fileURL: invalidURL)
        ) { error in
            XCTAssertEqual(error.localizedDescription, "The Excel workbook could not be opened.")
        }
    }

    func testMalformedXLSReturnsReadableError() throws {
        let importer = XLSBinaryTransactionImporter()
        let invalidURL = FileManager.default.temporaryDirectory
            .appendingPathComponent(UUID().uuidString)
            .appendingPathExtension("xls")
        try Data("not a workbook".utf8).write(to: invalidURL)
        defer { try? FileManager.default.removeItem(at: invalidURL) }

        XCTAssertThrowsError(
            try importer.makeDraft(fileName: invalidURL.lastPathComponent, fileURL: invalidURL)
        ) { error in
            XCTAssertFalse(error.localizedDescription.isEmpty)
        }
    }

    func testOversizedImportFailsBeforeParsingWithReadableError() throws {
        let oversizedURL = FileManager.default.temporaryDirectory
            .appendingPathComponent(UUID().uuidString)
            .appendingPathExtension("csv")
        FileManager.default.createFile(atPath: oversizedURL.path, contents: nil)
        defer { try? FileManager.default.removeItem(at: oversizedURL) }

        let handle = try FileHandle(forWritingTo: oversizedURL)
        try handle.truncate(atOffset: UInt64(ImportPreparationService.maxImportFileSizeBytes + 1))
        try handle.close()

        let outcome = ImportPreparationService.prepareDraft(from: oversizedURL)

        guard case let .failure(message) = outcome else {
            return XCTFail("Expected oversized import to fail")
        }
        XCTAssertTrue(message.localizedStandardContains("too large"))
        XCTAssertTrue(message.localizedStandardContains("under"))
    }

    private func makeReadyGemmaModelManager() throws -> GemmaModelManager {
        let fileManager = FileManager.default
        let rootDirectory = fileManager.temporaryDirectory.appendingPathComponent(UUID().uuidString, isDirectory: true)
        let manager = GemmaModelManager(
            fileManager: fileManager,
            appSupportDirectory: rootDirectory,
            adoptableSourceURLs: [],
            minimumValidModelSizeBytes: 32
        )
        try fileManager.createDirectory(at: manager.modelsDirectoryURL, withIntermediateDirectories: true)
        try Self.makeValidGGUFModel(totalBytes: 64).write(to: manager.managedModelURL)
        return manager
    }

    private static func makeValidGGUFModel(totalBytes: Int) -> Data {
        var data = Data("GGUF".utf8)
        if totalBytes > data.count {
            data.append(Data(repeating: 0x41, count: totalBytes - data.count))
        }
        return data
    }
}

private actor RecordingMerchantClassificationIntelligence: MerchantClassificationIntelligence {
    private var recordedBatchSizes: [Int] = []

    func classifyMerchant(
        rawMerchant: String,
        memo: String?,
        category: String?,
        amount: Decimal
    ) async throws -> MerchantClassificationResult? {
        MerchantClassificationResult(
            canonicalName: rawMerchant,
            serviceCategory: category ?? "Uncategorized",
            merchantKind: .softwareOrSaaS,
            subscriptionAffinity: 0.8,
            confidence: 0.7
        )
    }

    func classifyMerchantsBatch(
        _ requests: [MerchantClassificationRequest]
    ) async throws -> [String: MerchantClassificationResult]? {
        recordedBatchSizes.append(requests.count)

        return Dictionary(uniqueKeysWithValues: requests.map { request in
            (
                request.rawMerchant,
                MerchantClassificationResult(
                    canonicalName: request.rawMerchant,
                    serviceCategory: request.category ?? "Uncategorized",
                    merchantKind: .softwareOrSaaS,
                    subscriptionAffinity: 0.8,
                    confidence: 0.7
                )
            )
        })
    }

    func batchSizes() -> [Int] {
        recordedBatchSizes
    }
}

private actor FailingMerchantClassificationIntelligence: MerchantClassificationIntelligence {
    func classifyMerchant(
        rawMerchant: String,
        memo: String?,
        category: String?,
        amount: Decimal
    ) async throws -> MerchantClassificationResult? {
        nil
    }

    func classifyMerchantsBatch(
        _ requests: [MerchantClassificationRequest]
    ) async throws -> [String: MerchantClassificationResult]? {
        nil
    }
}

private actor PartiallyFailingBatchMerchantClassificationIntelligence: MerchantClassificationIntelligence {
    private var batchCallCount = 0

    func classifyMerchant(
        rawMerchant: String,
        memo: String?,
        category: String?,
        amount: Decimal
    ) async throws -> MerchantClassificationResult? {
        MerchantClassificationResult(
            canonicalName: rawMerchant,
            serviceCategory: category ?? "Uncategorized",
            merchantKind: .softwareOrSaaS,
            subscriptionAffinity: 0.8,
            confidence: 0.7
        )
    }

    func classifyMerchantsBatch(
        _ requests: [MerchantClassificationRequest]
    ) async throws -> [String: MerchantClassificationResult]? {
        batchCallCount += 1

        guard batchCallCount == 1 else {
            return nil
        }

        return Dictionary(uniqueKeysWithValues: requests.map { request in
            (
                request.rawMerchant,
                MerchantClassificationResult(
                    canonicalName: request.rawMerchant,
                    serviceCategory: request.category ?? "Uncategorized",
                    merchantKind: .softwareOrSaaS,
                    subscriptionAffinity: 0.8,
                    confidence: 0.7
                )
            )
        })
    }
}

private actor SubsetBatchMerchantClassificationIntelligence: MerchantClassificationIntelligence {
    func classifyMerchant(
        rawMerchant: String,
        memo: String?,
        category: String?,
        amount: Decimal
    ) async throws -> MerchantClassificationResult? {
        MerchantClassificationResult(
            canonicalName: "AI \(rawMerchant)",
            serviceCategory: category ?? "Uncategorized",
            merchantKind: .softwareOrSaaS,
            subscriptionAffinity: 0.8,
            confidence: 0.7
        )
    }

    func classifyMerchantsBatch(
        _ requests: [MerchantClassificationRequest]
    ) async throws -> [String: MerchantClassificationResult]? {
        Dictionary(uniqueKeysWithValues: requests.dropFirst().map { request in
            (
                request.rawMerchant,
                MerchantClassificationResult(
                    canonicalName: "AI \(request.rawMerchant)",
                    serviceCategory: request.category ?? "Uncategorized",
                    merchantKind: .softwareOrSaaS,
                    subscriptionAffinity: 0.8,
                    confidence: 0.7
                )
            )
        })
    }
}

private actor CancellingBatchMerchantClassificationIntelligence: MerchantClassificationIntelligence {
    private var callCount = 0

    func classifyMerchant(
        rawMerchant: String,
        memo: String?,
        category: String?,
        amount: Decimal
    ) async throws -> MerchantClassificationResult? {
        nil
    }

    func classifyMerchantsBatch(
        _ requests: [MerchantClassificationRequest]
    ) async throws -> [String: MerchantClassificationResult]? {
        callCount += 1
        throw CancellationError()
    }

    func batchCallCount() -> Int {
        callCount
    }
}

private actor CancellingIndividualMerchantClassificationIntelligence: MerchantClassificationIntelligence {
    private var callCount = 0

    func classifyMerchant(
        rawMerchant: String,
        memo: String?,
        category: String?,
        amount: Decimal
    ) async throws -> MerchantClassificationResult? {
        callCount += 1
        throw CancellationError()
    }

    func classifyMerchantsBatch(
        _ requests: [MerchantClassificationRequest]
    ) async throws -> [String: MerchantClassificationResult]? {
        XCTFail("Individual strategy should not call batch classification")
        return nil
    }

    func merchantCallCount() -> Int {
        callCount
    }
}
