#!/usr/bin/env node

import { execFileSync } from 'node:child_process';
import { mkdtempSync, rmSync, mkdirSync, readFileSync, writeFileSync, copyFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';

const repoRoot = process.cwd();
const assetsRoot = join(repoRoot, 'Tally', 'Resources', 'BrandLogos.xcassets');
const generatedSwiftPath = join(repoRoot, 'Tally', 'Shared', 'GeneratedServiceLogoManifest.swift');
const sourcesDocPath = join(repoRoot, 'Tally', 'Resources', 'BrandLogos-SOURCES.md');

const simpleIconsVersion = '16.11.0';
const tempRoot = mkdtempSync(join(tmpdir(), 'subtracker-service-logos-'));
const simpleIconsRoot = join(tempRoot, 'simple-icons-source');

const svglSupplements = [
  {
    title: 'OpenAI',
    assetSlug: 'openai',
    aliases: ['chatgpt', 'chatgptplus', 'chatgptpro', 'openaiapi'],
  },
  {
    title: 'Anthropic',
    assetSlug: 'anthropic',
    aliases: ['claude', 'claudeai', 'claudepro'],
  },
];

const customAliasOverrides = {
  amazonprime: ['primevideo', 'amazonvideo', 'amazonprimevideo'],
  apple: ['appleone', 'appleservices'],
  appletv: ['appletvplus', 'tvplus'],
  applemusic: ['applemusicfamily', 'itunes'],
  disneyplus: ['disney', 'disneybundle'],
  google: ['googleworkspace'],
  googleplay: ['googleplaypass'],
  hbo: ['hbomax'],
  icloud: ['icloudplus'],
  microsoft: ['microsoft365', 'office365', 'office'],
  netflix: ['netflixcom'],
  openai: ['chatgptteam'],
  youtube: ['youtubepremium', 'youtubepremiumfamily', 'youtubepremiumlite', 'youtubemusic'],
};

const normalize = (value) =>
  value
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '');

const ensureDir = (path) => mkdirSync(path, { recursive: true });

const writeJson = (path, value) => writeFileSync(path, `${JSON.stringify(value, null, 2)}\n`);

const flattenAliases = (value, output = []) => {
  if (!value) return output;
  if (typeof value === 'string') {
    output.push(value);
    return output;
  }
  if (Array.isArray(value)) {
    for (const item of value) flattenAliases(item, output);
    return output;
  }
  if (typeof value === 'object') {
    for (const item of Object.values(value)) flattenAliases(item, output);
  }
  return output;
};

const assetContents = (filename) => ({
  images: [
    {
      filename,
      idiom: 'universal',
    },
  ],
  info: {
    author: 'xcode',
    version: 1,
  },
  properties: {
    'preserves-vector-representation': true,
    'template-rendering-intent': 'original',
  },
});

const installSimpleIcons = () => {
  execFileSync(
    'npm',
    ['install', '--prefix', simpleIconsRoot, `simple-icons@${simpleIconsVersion}`],
    { stdio: 'inherit' }
  );
};

const fetchJson = async (url) => {
  const response = await fetch(url, {
    headers: {
      'User-Agent': 'Tally Logo Sync',
      Accept: 'application/json',
    },
  });
  if (!response.ok) {
    throw new Error(`Failed to fetch ${url}: ${response.status}`);
  }
  return response.json();
};

const fetchText = async (url) => {
  const response = await fetch(url, {
    headers: {
      'User-Agent': 'Tally Logo Sync',
      Accept: 'image/svg+xml,text/plain,*/*',
    },
  });
  if (!response.ok) {
    throw new Error(`Failed to fetch ${url}: ${response.status}`);
  }
  return response.text();
};

const resetGeneratedOutputs = () => {
  rmSync(assetsRoot, { recursive: true, force: true });
  ensureDir(assetsRoot);
  writeJson(join(assetsRoot, 'Contents.json'), {
    info: {
      author: 'xcode',
      version: 1,
    },
  });
};

const toSwiftArray = (items) => `[${items.map((item) => `"${item}"`).join(', ')}]`;

const writeGeneratedSwift = (entries) => {
  const lines = [
    '// This file is generated by scripts/generate_service_logos.mjs.',
    '// Sources: Simple Icons 16.11.0 (CC0-1.0) and SVGL supplements.',
    '',
    'import Foundation',
    '',
    'enum GeneratedServiceLogoManifest {',
    '    static let entries: [ServiceLogoDatabase.Entry] = [',
  ];

  for (const entry of entries) {
    lines.push(
      `        .init(assetName: "${entry.assetName}", aliases: ${toSwiftArray(entry.aliases)}),`
    );
  }

  lines.push('    ]', '}');
  writeFileSync(generatedSwiftPath, `${lines.join('\n')}\n`);
};

const writeSourcesDoc = (counts) => {
  writeFileSync(
    sourcesDocPath,
    [
      '# Brand Logo Sources',
      '',
      '- Bulk dataset: `simple-icons@16.11.0`',
      '  - Homepage: <https://simpleicons.org>',
      '  - License: `CC0-1.0`',
      `  - Bundled icons: ${counts.simpleIcons}`,
      '- Supplemental dataset: `SVGL`',
      '  - Homepage: <https://svgl.app>',
      '  - Repository: <https://github.com/pheralb/svgl>',
      '  - Supplemental bundled icons: OpenAI, Anthropic',
      '',
      'The app bundles these SVGs locally and does not fetch logos at runtime.',
      '',
    ].join('\n')
  );
};

const buildEntries = async () => {
  installSimpleIcons();

  const simpleIconsDataPath = join(simpleIconsRoot, 'node_modules', 'simple-icons', 'data', 'simple-icons.json');
  const simpleIconsIconsPath = join(simpleIconsRoot, 'node_modules', 'simple-icons', 'icons');
  const simpleIcons = JSON.parse(readFileSync(simpleIconsDataPath, 'utf8'));

  const svglItems = await fetchJson('https://api.svgl.app');
  const svglByTitle = new Map(svglItems.map((item) => [item.title, item]));

  const entries = [];
  const seenAssets = new Set();

  for (const icon of simpleIcons) {
    const assetName = `brand-${icon.slug}`;
    const imageSetDir = join(assetsRoot, `${assetName}.imageset`);
    const sourceSvg = join(simpleIconsIconsPath, `${icon.slug}.svg`);
    const targetSvg = join(imageSetDir, `${assetName}.svg`);
    const aliases = new Set([
      icon.title,
      icon.slug,
      ...flattenAliases(icon.aliases),
      ...(customAliasOverrides[icon.slug] ?? []),
    ].map(normalize).filter(Boolean));

    ensureDir(imageSetDir);
    copyFileSync(sourceSvg, targetSvg);
    writeJson(join(imageSetDir, 'Contents.json'), assetContents(`${assetName}.svg`));

    entries.push({
      assetName,
      aliases: [...aliases].sort(),
    });
    seenAssets.add(normalize(icon.title));
    seenAssets.add(normalize(icon.slug));
  }

  for (const supplement of svglSupplements) {
    if (seenAssets.has(normalize(supplement.title)) || seenAssets.has(normalize(supplement.assetSlug))) {
      continue;
    }

    const item = svglByTitle.get(supplement.title);
    if (!item) {
      throw new Error(`Missing SVGL supplement for ${supplement.title}`);
    }

    const route = typeof item.route === 'string' ? item.route : item.route.light ?? item.route.dark;
    const svg = await fetchText(route);
    const assetName = `brand-${supplement.assetSlug}`;
    const imageSetDir = join(assetsRoot, `${assetName}.imageset`);
    const svgName = `${assetName}.svg`;

    ensureDir(imageSetDir);
    writeFileSync(join(imageSetDir, svgName), svg);
    writeJson(join(imageSetDir, 'Contents.json'), assetContents(svgName));

    const aliases = new Set([
      supplement.title,
      supplement.assetSlug,
      ...(supplement.aliases ?? []),
    ].map(normalize).filter(Boolean));

    entries.push({
      assetName,
      aliases: [...aliases].sort(),
    });
  }

  entries.sort((left, right) => left.assetName.localeCompare(right.assetName));
  return {
    entries,
    simpleIconsCount: simpleIcons.length,
  };
};

const main = async () => {
  resetGeneratedOutputs();
  const { entries, simpleIconsCount } = await buildEntries();
  writeGeneratedSwift(entries);
  writeSourcesDoc({ simpleIcons: simpleIconsCount });
  console.log(`Generated ${entries.length} service logo entries.`);
};

main().finally(() => {
  rmSync(tempRoot, { recursive: true, force: true });
}).catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
